### ISSUE TITLE
Process exited with code 1 Stderr

### ISSUE THREAD

**Issue by mrbase1** [onlook-dev/onlook#1243]
After prompting, I get this error:

Process exited with code 1 Stderr: 'C:\Users\Mr' is not recognized as an internal or external command, operable program or batch file.

![Image](https://github.com/user-attachments/assets/e7896777-a4b7-4c99-a2b3-6f3994862b47)

**Comment by Kitenite** [comment]
Hey @mrbase1, thank you for reporting. Is this on Mac or Windows?

**Comment by mrbase1** [comment]
> Hey [@mrbase1](https://github.com/mrbase1), thank you for reporting. Is this on Mac or Windows?

on Windows

**Comment by Kitenite** [comment]
I think I see the issue. Working on a fix right now. 
In the meantime, you can use this older version https://github.com/onlook-dev/onlook/releases/download/v0.1.34/Onlook-setup.exe

Sorry for the issue

**Comment by Kitenite** [comment]
Hey @mrbase1,
I merged in a fix for this. Building a release right now hoping to get a new version out in 10 mins after some more testing.
https://github.com/onlook-dev/onlook/pull/1245

**Comment by mrbase1** [comment]
This is an awesome and very welcome response. Thanks Kitenite!

**Comment by Kitenite** [comment]
@mrbase1 , I released the fix. It should show an option to update after a few minutes. Thanks for your patience and lmk if the issue still persists!

https://github.com/onlook-dev/onlook/releases/tag/v0.1.36

**Comment by mrbase1** [comment]
Thanks @Kitenite

**Comment by mrbase1** [comment]
Hi @Kitenite, after I reinstalled, I got a new error immediately after prompting:

![Image](https://github.com/user-attachments/assets/e217e22e-b11e-4a69-8e50-380279034cef)

Since I haven't been asked to provide more than the prompt, there's nothing to be done on my end. If there is, please advise.

**Comment by Kitenite** [comment]
>  I got a new error immediately after prompting:

Hmm... at least it's a new error. I'm certain that the root cause is that there are special characters in the path to the project. I will work on this soon.

**Comment by mrbase1** [comment]
Thanks @Kitenite

**Comment by Kitenite** [comment]
Hey @mrbase1 ,
I just released another update. Could you try again and let me know if it's solved now? Thank you for your patience

**Comment by mrbase1** [comment]
I'll try it now, thanks

**Comment by mrbase1** [comment]
I'll try it now, thanks

**Comment by mrbase1** [comment]
So I had the same issue this time; then I decided to install afresh on a different Windows system to see how it behaves. On the second Windows system I got this error:

spawn "'C:\\\\Mr Base1\\\\AppData\\\\Local\\\\Programs\\\\@Onlookstudio\\\\resources\\\\bun\\\\bun.exe
ENOENT

Again, this is coming immediately after prompting.

**Comment by mrbase1** [comment]
Sorry for being such a bother, but I'm still unable to use the app.

![Image](https://github.com/user-attachments/assets/6df6893d-75d5-4c4b-9d2e-3833f7ff7521)

Eager to give it a try but I can't get past this

**Comment by Kitenite** [comment]
Hey @mrbase1, 
Not a bother. I've been trying to figure out a solve for this over the last few days. I'm testing a fix still. Thank you for the patience. It's narrowed down to there being a space in the username which we're not handling well.

**Comment by mrbase1** [comment]
Yea @Kitenite 
My mind has been on that space as well. Hope a fix can be found, but I'll also change my username on one of the PCs to check. Also, I'm in celebration mode cos I finally got my MacBook to boot up this night. I'll set up on the Mac and give the app a try

**Comment by Kitenite** [comment]
That's awesome! Let me know how it goes :)

**Comment by mrbase1** [comment]
> That's awesome! Let me know how it goes :)

Sadly I need to buy a new battery first. The MacBook keeps reporting false battery levels.

**Comment by mrbase1** [comment]
Its working!!! I generated a business directory app and it looks great out of the box!

Before we close this chat, it seems I hit a rate limit pretty quick but I can't find the info on rate limits for free use. Can you help me with a link to the info?

**Comment by mrbase1** [comment]
Oh ok, I found the info in the FAQs. 5 messages daily. Stopped my celebration really fast. But the Onlook is looking awesome!!

Great work guys!

**Comment by Kitenite** [comment]
Hey @mrbase1 , 
Please come say hi in the Discord, I'd love to help with a workaround
https://discord.gg/hERDfFZCsH
